cluster/README.txt
Found while I was checking out the repo. Just a lil' change!
=> fixes typo in README.txt

crawler/README.txt, crawler/crawl.py, crawler/crawling.py, crawler/reporting.py
Use "aiohttp" package instead of reimplementing HTTP protocol. This lets us simplify the example to focus on async I/O and coroutines.
Refactor the control flow to use a JoinableQueue since that's my specialty.
=> Update web crawler example code.

pedometer/chapter.md
Additional minor language tweaks and spacing changes.
=> Language tweaks

spreadsheet/chapter.md
Copyedits to the Spreadsheet chapter
=> Spreadsheet edits

modeller/chapter.md
=> Modeller edits

modeller/chapter.md
@amyrbrown I was having trouble figuring out how to submit a pull request to your fork (it doesn't show up in the dropdown menu for me under "base fork"), so I'm adding a pull request to the main repo.
I've gone into more depth about the diagram, explicitly stating that we don't need to worry about the right hand side. I've also explicitly mentioned that "mesh" can be used interchangeably with "model".
Let me know what you think! I'm happy to make further adjustments to improve clarity.
=> add more depth to description of the diagram

ci/chapter.rst
Hi @malini (and congratulations on your new job!). I have copyedited your chapter and am submitting this PR against the aosabook repo. I'm going to make a few comments on the PR where I have questions or I want to explain why I have made a change.
Please have a look at my changes and comments. As we discuss the chapter, I'll make any further changes to my fork, and once we're both happy with it I'll let @MichaelDiBernardo know that the PR is ready to merge.
Thank you!
=> Copyedits to CI chapter

static-analysis/StaticAnalysisChapter.md
I've added the beginning (intro sections) of the chapter. I'm going to add 4 more sections, one for each of three "checks" that TypeCheck can make.
There probably needs to be more "this is how this works in Julia" notes added to the early code examples.
=> Adding Text to Static Analysis Chapter

flow-shop/chapter.md
Maybe you're not micromanaging -- but I am! :)
=> One tiny change to make pronoun agree

cluster/CHAPTER.rst
See comments and queries inline. Some of my changes are converting from RST to MD (which is not complete), there are some spelling fixes, and other things.
=> Copyedits to the Paxos clustering chapter

README.md
Slightly more accurate, avoids giving the wrong impression.
=> Updates my affiliations

README.md
Though I remember reading the instructions, I apparently forgot to add us to the README when creating our chapter pull request. So here you go — thanks!
=> Add "contingent" chapter authors to README.md

README.md
Looks like I also forgot to add myself to the README in my original pull request. Thanks for the reminder, Brandon!
=> Add dagoba author to README.md

data-store/chapter.md
Some changes in wording and format, and one query (line 497)
=> Copyedits for DBDB chapter

crawler/code/crawling.py, crawler/code/requirements-py33.txt, crawler/code/requirements-py34.txt, crawler/crawler.markdown
@asvetlov would you mind reviewing please?
=> Crawler updates

static-analysis/StaticAnalysisChapter.md
Mostly little punctuation and format changes.
=> Edits to Static Analysis chapter

crawler/code/crawl.py, crawler/code/crawling.py, crawler/code/test.py
@ajdavis  there is promised PR for correct resource cleanup
=> Gracefully close aiohttp session and responses

crawler/crawler.markdown
Now that the example code has switched from using bare aiohttp.Request
to the connection-pooling aiohttp.ClientSession, I finish updating the
code blocks in the chapter text, and show how to release the connection
back to the pool.
=> crawler.markdown fixes for aiohttp.ClientSession.

crawler/crawler.markdown
Else the code would throw a NameError.
=> Import module constant

crawler/crawler.markdown
Otherwise the attribute seems to never be set.
=> Make Crawler.loop actually exist

functionalDB/functionalDB.markdown
@MichaelDiBernardo please let me know if there are still lines that need trimming
=> adapting length of code lines to 85 columns

interpreter/chapter.txt
Here are my copyedits to the Byterun chapter. Nothing major, mostly just typo fixes and formatting changes. 
There are three queries in the PR, on (new) lines 144, 314, and 393.
=> Copyedits to Byterun Interpreter chapter

interpreter/chapter.txt
I'll leave this open for a few days before merging. @akaptur, if you'd like to take a different course of action on these, let me know!
Previous PR was https://github.com/aosabook/500lines/pull/146/
=> Addressing comments from copy-editing

template-engine/template-engine.markdown
=> remove redundant the

blockcode/blockcode.markdown
Just fixing up my name. Was wondering which chapter this would end up in the book, but didn't see it in the main Readme.
=> fix spelling

web-server/web-server.markdown
As usual, editing @gvwilson's writing is boring as hell with almost nothing to change or fix. SIGH. I did manage to find a couple of things to complain about -- see comments in the "Files changed" view.
=> Edits to the web server chapter.

web-server/web-server.markdown
From edits made in https://github.com/aosabook/500lines/pull/192.
Re: the images -- since we're keeping the first two, I was loathe to create a new version of the third one (it's in the same style.) I think we're good to ship the web version with the current set of images, and if @gvwilson has an opportunity to make the suggested changes to the cycle image before we go to print, we'll backport the changes to web then.
@amyrbrown, would you mind taking one last look at the couple of edits I did here?
=> Revisions to web-server chapter

dagoba/dagoba.markdown
I've made all the changes listed in my previous PR comment. Probably 50% of the differences are removal of trailing whitespace, 25% are whitespace re-alignment, and of the remainder I think only a handful will be interesting. 
A few particular items to call to attention: in lines 1 and 364 I've created new footnotes, and in line 366 there is a '[citation]' block that probably needs different formatting.
=> Dagoba edits

dagoba/dagoba.markdown
Just removing an errant ending bracket from a footnote.
=> removed ending bracket

image-filters/image-filters.markdown
Here are the copyedits for this chapter. It was interesting and a fun project to read about. 
I made a fair number of changes for clarity and readability, hopefully without sacrificing the friendly, conversational tone of the writing. @catehstn, please have a look at my changes (or the final version, if that's easier) and let me know if you have any questions or concerns. I think the best way to deal with further changes at this stage is for me to make them on my copy of the repo and update this PR.
There are also a couple of comments on the Files Changed view which need some attention.
Thank you!
=> Copyedits to Image Filters chapter

spreadsheet/spreadsheet.zh-tw.markdown
@MichaelDiBernardo Please help to review. Thanks!
=> fix images location

event-web-framework/event-web-framework.markdown
Here are my copyedits on this chapter. Let me know if there are any questions or comments!
=> Edits to the Event-Drive Web Framework chapter

minutiae/intro.tex
I fixed a few little things in the introduction and bios. More notes on the File Changed page. (I really like the Introduction!)
=> Edits to Introduction and bios
